### ISSUE TITLE
Ubuntu base images

### ISSUE THREAD

**Issue by alexcrichton** [sfackler/docker-rust#3]
I'm actually pretty new to the concept of "official" images, but do you know if there's a "generally accepted" practice of base images? The shell code in the debian-generated images is easy enough to copy around, but I'm not sure if there's a practice for what "base images" should be used.

In lieu of that, though, maybe some ubuntu images could be provided as well?

This is sort of a more general question, I'm not really sure at all what idiomatic "official" containers look like

**Comment by sfackler** [comment]
There's an outline on "standard" base images here: https://github.com/docker-library/golang/pull/139#issuecomment-282449905.

TL;DR: Debian/Alpine/Windows

**Comment by alexcrichton** [comment]
:+1: sgtm

**Comment by mhsjlw** [comment]
Why isn't alpine being used?

**Comment by sfackler** [comment]
There is no version of rustc built to run on Alpine at the moment.
